-- Sample recruiters
INSERT OR IGNORE INTO users (id, email, password, role, name) VALUES 
(1, 'hr@techcorp.com', '$2a$10$rOvHPxfzDNhL8UQUB9l5/.pJ3OXRdAHHGGGvK5x5x5x5x5x5x5x5x', 'recruiter', 'Tech Corp HR'),
(2, 'hiring@startupxyz.com', '$2a$10$rOvHPxfzDNhL8UQUB9l5/.pJ3OXRdAHHGGGvK5x5x5x5x5x5x5x5x', 'recruiter', 'StartupXYZ Hiring'),
(3, 'talent@datacorp.com', '$2a$10$rOvHPxfzDNhL8UQUB9l5/.pJ3OXRdAHHGGGvK5x5x5x5x5x5x5x5x', 'recruiter', 'DataCorp Talent');

-- Sample applications with AI insights
INSERT OR IGNORE INTO applications (id, job_id, candidate_name, candidate_email, candidate_phone, ai_score, test_score, status, ai_insights, created_at) VALUES 
(1, 1, 'Sarah Johnson', 'sarah.johnson@email.com', '+1-555-0123', 87, 92, 'test_completed', '{"skills_matched":[{"skill":"JavaScript","category":"programming","level":"expert"},{"skill":"React","category":"frontend","level":"expert"},{"skill":"Node.js","category":"backend","level":"intermediate"}],"skill_gaps":[{"skill":"TypeScript","category":"programming","priority":"medium"}],"certifications":["AWS Certified Developer"],"education":{"level":"bachelors","field":"computer science"},"experience_years":6,"strengths":["Strong frontend skills","Full-stack capabilities"],"recommendations":["Consider AWS certification"],"industry_experience":["fintech","saas"]}', datetime('now', '-3 days')),

(2, 2, 'Michael Chen', 'michael.chen@email.com', '+1-555-0124', 78, 85, 'test_completed', '{"skills_matched":[{"skill":"React","category":"frontend","level":"expert"},{"skill":"JavaScript","category":"programming","level":"intermediate"}],"skill_gaps":[{"skill":"Redux","category":"frontend","priority":"high"}],"certifications":["Google Analytics Certified"],"education":{"level":"bachelors","field":"web development"},"experience_years":4,"strengths":["UI/UX focus","Modern React patterns"],"recommendations":["Learn Redux for state management"],"industry_experience":["e-commerce","startup"]}', datetime('now', '-5 days')),

(3, 3, 'Dr. Emily Rodriguez', 'emily.rodriguez@email.com', '+1-555-0125', 94, 88, 'test_completed', '{"skills_matched":[{"skill":"Python","category":"programming","level":"expert"},{"skill":"Machine Learning","category":"data","level":"expert"},{"skill":"SQL","category":"database","level":"expert"}],"skill_gaps":[{"skill":"Deep Learning","category":"data","priority":"medium"}],"certifications":["Google Cloud ML Engineer","Coursera ML Specialization"],"education":{"level":"phd","field":"data science"},"experience_years":8,"strengths":["Advanced statistical knowledge","Research background"],"recommendations":["Explore deep learning frameworks"],"industry_experience":["healthcare","fintech"]}', datetime('now', '-1 days')),

(4, 4, 'Alex Thompson', 'alex.thompson@email.com', '+1-555-0126', 72, 79, 'test_completed', '{"skills_matched":[{"skill":"Google Ads","category":"marketing","level":"expert"},{"skill":"Analytics","category":"marketing","level":"intermediate"}],"skill_gaps":[{"skill":"Facebook Ads","category":"marketing","priority":"high"}],"certifications":["Google Ads Certified","HubSpot Certified"],"education":{"level":"bachelors","field":"marketing"},"experience_years":5,"strengths":["PPC expertise","Data-driven approach"],"recommendations":["Expand social media advertising skills"],"industry_experience":["e-commerce","saas"]}', datetime('now', '-7 days')),

(5, 1, 'David Kim', 'david.kim@email.com', '+1-555-0127', 65, NULL, 'not_eligible', '{"skills_matched":[{"skill":"JavaScript","category":"programming","level":"beginner"}],"skill_gaps":[{"skill":"React","category":"frontend","priority":"high"},{"skill":"Node.js","category":"backend","priority":"high"}],"certifications":[],"education":{"level":"bachelors","field":"computer science"},"experience_years":1,"strengths":["Basic programming knowledge","Eager to learn"],"recommendations":["Gain more hands-on experience","Learn modern frameworks"],"industry_experience":[]}', datetime('now', '-2 days')),

(6, 5, 'Lisa Wang', 'lisa.wang@email.com', '+1-555-0128', 81, 87, 'test_completed', '{"skills_matched":[{"skill":"JavaScript","category":"programming","level":"expert"},{"skill":"React","category":"frontend","level":"intermediate"},{"skill":"Node.js","category":"backend","level":"intermediate"}],"skill_gaps":[{"skill":"TypeScript","category":"programming","priority":"medium"}],"certifications":["MongoDB Certified Developer"],"education":{"level":"masters","field":"computer science"},"experience_years":5,"strengths":["Full-stack capabilities","Modern tech stack"],"recommendations":["Add TypeScript to skill set"],"industry_experience":["startup","saas"]}', datetime('now', '-4 days')),

(7, 6, 'James Wilson', 'james.wilson@email.com', '+1-555-0129', 89, 91, 'test_completed', '{"skills_matched":[{"skill":"Python","category":"programming","level":"expert"},{"skill":"TensorFlow","category":"data","level":"expert"},{"skill":"Machine Learning","category":"data","level":"expert"}],"skill_gaps":[{"skill":"MLOps","category":"data","priority":"medium"}],"certifications":["TensorFlow Developer Certificate","AWS ML Specialty"],"education":{"level":"masters","field":"machine learning"},"experience_years":6,"strengths":["Deep learning expertise","Model deployment experience"],"recommendations":["Focus on MLOps practices"],"industry_experience":["healthcare","fintech"]}', datetime('now', '-6 days')),

(8, 2, 'Anna Martinez', 'anna.martinez@email.com', '+1-555-0130', 69, NULL, 'not_eligible', '{"skills_matched":[{"skill":"HTML","category":"frontend","level":"intermediate"},{"skill":"CSS","category":"frontend","level":"intermediate"}],"skill_gaps":[{"skill":"React","category":"frontend","priority":"high"},{"skill":"Modern JavaScript","category":"programming","priority":"high"}],"certifications":[],"education":{"level":"bachelors","field":"web design"},"experience_years":2,"strengths":["Design sense","Basic web technologies"],"recommendations":["Learn React framework","Strengthen JavaScript skills"],"industry_experience":["design agency"]}', datetime('now', '-8 days'));